### PR TITLE
Caching and an additional action

### PR DESCRIPTION
**Pull request by novoid**
Hi,
I've implemented caching to the contacts since it takes quite long to parse the more or less static list of contacts in my case.
Feel free to drop any of my other changes. To be quite frankly, I could not figure out how to create a pull request only for selected commits. :-(
The two commits of interest for you should be the ones whose commit messages start with "added...".

### CODE REVIEW

**Comment by tmalsburg** [comment]
Hey thanks, both additions look useful.  Regarding caching, with your PR users refresh the cache manually.  Correct?  It would be more convenient to watch the file and to trigger rereading automatically via `file-notify-add-watch`.  I'll add something along those lines.

**Comment by tmalsburg** [comment]
Just committed a caching mechanism. Should also work if the contacts file changes.  Could you please test whether this works for you?  Thanks.

**Comment by tmalsburg** [comment]
Regarding the contact links, could you please post an example entry from you contacts?  Your action doesn't work with my format because there is no "nametag".  What's a nametag?

**Comment by tmalsburg** [comment]
Your code also accesses the FN property but I was under the impression that the heading of the entry contains the formatted name (i.e. FN).  See the examples [here](https://github.com/tmalsburg/helm-org-contacts).

**Comment by novoid** [comment]
> Hey thanks, both additions look useful. Regarding caching, with your PR users refresh the cache manually. Correct?

Yes, that's correct.

I can not use any automated concept since re-caching takes up to fifty seconds on my side. So whenever I save my `contacts.org`, Emacs would block for almost a minute which is a no-go.

**Comment by novoid** [comment]
> could you please post an example entry from you contacts?

https://www.karl-voit.at/2015/02/01/muttfilter/ shows an example

**Comment by novoid** [comment]
> What's a nametag?

Every contact has at least one tag associated which concatenates first and lastname. So for example, "Joe Average" has `:JoeAverage:` as first tag. "nametag" therefore refers to the first tag of the heading.

Background: I'm using this for a custom link to the contact. I prefer tags over IDs because it might be the case that I have multiple entries for FirstLast and I want to get all potential candidates highlighted when accessing.

**Comment by novoid** [comment]
> Could you please test whether this works for you?

Sorry, for the reason already mentioned above, I can not use any auto-update mechanism which would be a DoS-attack on my Org mode session.

**Comment by tmalsburg** [comment]
Reloading takes 50s on your system? wow.  May I ask how many entries you have?  Extrapolating from my setup (older Thinkpad) you'd have to have 25k entries or so.  Or you're hitting a performance bug that we should fix.

Regarding the links, if the nametag is a custom solution, I'd rather not include it.  But if there was a generic solution that works for users of vanilla org-contacts, that would of course be great.

**Comment by tmalsburg** [comment]
I've added an "insert link to contact" action.  It uses the :FN as the target.

**Comment by tmalsburg** [comment]
I've also added a variable `helm-org-contacts-autoreload` that you can set to `nil` to prevent automatic reloading.  If you want to force a reload, you can do this with a prefix argument, i.e. `C-u helm-org-contacts`.  Does that work for you?

**Comment by novoid** [comment]
> May I ask how many entries you have? Extrapolating from my setup (older Thinkpad) you'd have to have 25k entries or so. Or you're hitting a performance bug that we should fix.

Approximately 2500 contacts in 88,000 lines of Org mode. So it's not just contact information headings but also todos, quotes, notes, and so forth.

I'm not sure of this is [one of my performance issues](https://www.reddit.com/r/orgmode/comments/e9p84n/scaling_org_better_to_use_more_medsize_files_or/) or not.

**Comment by novoid** [comment]
> Does that work for you?

This sounds perfectly fine.

I'm not sure if I switch from my custom code to your general code because of some of my customizations I'd have to re-apply. I just wanted to make sure that the general user of you awesome feature is able to profit from the cache.

When the general code has advanced much more, I'd probably reconsider switching to the general code and re-implementing my own customizations (tag, different display of search hits, ...).

**Comment by tmalsburg** [comment]
> Approximately 2500 contacts in 88,000 lines of Org mode. So it's not just contact information headings but also todos, quotes, notes, and so forth.

I see. To avoid performance issues, I decided to keep different types of information in different files. I have files for to-do items, reminders and appointments, contacts, etc.  Makes working with org considerably more pleasant.

> I'm not sure if I switch from my custom code to your general code because of some of my customizations I'd have to re-apply.

What I usually do is to install the original package and to apply my changes in my Emacs init files.  This way, I can use my customizations and have the latest features.

Thanks for sharing your code and have a great day.

**Comment by novoid** [comment]
> I decided to keep different types of information in different files. I have files for to-do items, reminders and appointments, contacts, etc. Makes working with org considerably more pleasant.

A very valid approach, especially considering performance.

However, I chose a different path: https://karl-voit.at/2019/09/25/using-orgmode/
On my side, I focus on the projects and keep all their data at one single spot. I even wrote my own blog software to be able to blog anywhere: https://github.com/novoid/lazyblorg

My `contacts.org` is somewhat special because of org-contact restrictions (and probably performance). In contrast to the other Org files, it is ordered by contacts (and not topics/environment/...). It only contains contacts and contact-specific tasks/events/notes.

**Comment by novoid** [comment]
> What I usually do is to install the original package and to apply my changes in my Emacs init files. This way, I can use my customizations and have the latest features.

This is a very good recommendation which I had not thought before (because I very rarely modify external elisp code). I'll think about that.

**Comment by tmalsburg** [comment]
Thanks for the links.  Always interesting and inspiring to see how other people are using org.

**Pull request closed without merging**
